# MACEInputs configs
FILLER = '__XXX__'
MIN_ROWS = 2000
MIN_LABELS = 10
PRIORS_COL_NAME = 'PRIORS'
PRIORS_ANNOTATIONS_COL_NAME = 'Annotations'
CONTROLS_COL_NAME = 'CONTROLS'

# MACE configs
ALPHA = 0.5
BETA = 0.5
EM = False
ITERATIONS = 50
MAX_ITERATIONS = 1000
RESTARTS = 10
THRESHOLD = 1.0
